#!/bin/bash

to10() {
    s=0
    for ((i=0; i<${#1}; i++)); do
        case ${1:$i:1} in
            w) v=0;;
            a) v=1;;
            t) v=2;;
            e) v=3;;
            r) v=4;;
            s) v=0;;
            i) v=1;;
            *) v=2;;
        esac
        s=$((s*4+v))
    done
    echo $s
}

toBestchol() {
    n=$1; r=""
    chars=(b e s t c h o l)
    while ((n)); do
        r="${chars[n%8]}$r"
        n=$((n/8))
    done
    echo "$r"
}

sum=$(( $(to10 $WATER) + $(to10 $STIR) ))
toBestchol $sum

